name: Build & Production
on:
  push:
    tags:
      - 'release-*'

env:
  CONTAINER_REGISTRY: ghcr.io
  CONTAINER_REGISTRY_USER: ${{ secrets.GHCR_CONTAINER_REGISTRY_USER }}
  CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_REGISTRY_REPO: ghcr.io/city-of-helsinki/${{ github.event.repository.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  KUBECONFIG_RAW: ${{ secrets.KUBECONFIG_RAW_STABLE }}
  BUILD_ARTIFACT_FOLDER: 'build_artifacts'
  SERVICE_ARTIFACT_FOLDER: 'service_artifacts'
  SERVICE_PORT: 3000
  K8S_REQUEST_CPU: 100m
  K8S_REQUEST_RAM: 400Mi
  K8S_LIMIT_CPU: 1000m
  K8S_LIMIT_RAM: 800Mi
  K8S_REPLICACOUNT: 2

jobs:
  build:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: andersinno/kolga-build-action@v2
        env:
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-production
          DOCKER_BUILD_ARG_NEXT_PUBLIC_LINKED_EVENTS_URL: 'https://api.hel.fi/linkedevents/v1'
          DOCKER_BUILD_ARG_NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.GH_SENTRY_DSN }}
          DOCKER_BUILD_ARG_SENTRY_AUTH_TOKEN: ${{ secrets.GH_SENTRY_AUTH_TOKEN }}
          DOCKER_BUILD_ARG_NEXT_PUBLIC_ENVIRONMENT: 'production'
          DOCKER_BUILD_ARG_NEXT_PUBLIC_OIDC_AUTHORITY: 'https://api.hel.fi/sso'
          DOCKER_BUILD_ARG_NEXT_PUBLIC_OIDC_CLIENT_ID: 'linkedcomponents-ui-test'
          DOCKER_BUILD_ARG_NEXT_PUBLIC_OIDC_API_SCOPE: 'https://api.hel.fi/auth/linkedeventsdev'

  production:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: build
    name: Production
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v2

      - name: Deploy
        uses: andersinno/kolga-deploy-action@v2
        with:
          track: 'stable'
        env:
          K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE_STABLE }}
          K8S_ADDITIONAL_HOSTNAMES: ${{ secrets.K8S_ADDITIONAL_HOSTNAMES }}
          ENVIRONMENT_URL: https://${{ secrets.ENVIRONMENT_URL_STABLE }}
          DOCKER_IMAGE_NAME: ${{ env.REPO_NAME }}-production
